### ISSUE TITLE
Als Nutzer möchte ich eine Liste aller Nutzer in meiner Community einsehen können

### ISSUE THREAD

**Issue by Gerolmed** [MME-Aufgaben-im-Sommer-2022/mme-ss22-team-02#10]
Ich will auf der rechten Seite eine Leiste haben in der ich zum einen die Gesamtzahl an Usern in meiner Community sehe und zum anderen aber auch eine Liste in der Alle User aufgezählt sind.

**Comment by Cybun-s** [comment]
Funktion überflüssig, da Fokus auf Anfragen, nicht auf Communityfunktionen gelegt.
