### ISSUE TITLE
Als Administrator möchte ich neue Templates für Anfragen erstellen können

### ISSUE THREAD

**Issue by Gerolmed** [MME-Aufgaben-im-Sommer-2022/mme-ss22-team-02#12]
Als Administrator möchte ich neue Anfragetemplates erstellen können. So kann ich dann z.B. ein Template für spezifische Marktanfragen erstellen oder ein Template wo man neben Produktnamen auch noch die Marke angeben kann.

**Comment by Cybun-s** [comment]
Filtersystem nicht implementiert.
