### ISSUE TITLE
Als Nutzer möchte ich die Anfragen anhand vorgegebener Optionen filtern können

### ISSUE THREAD

**Issue by Gerolmed** [MME-Aufgaben-im-Sommer-2022/mme-ss22-team-02#15]
Sollte ich zu einem speziellen Laden fahren möchte ich in der Lage sein offene Anfragen so zu filtern, dass mir nur Anfragen für diesen Markt angezeigt werden können.

**Comment by Cybun-s** [comment]
Filter der Märkte nicht implementiert, da spezielle Produkte und deren Verkaufsort individuell per Chat besprochen werden können.
