### ISSUE TITLE
Als Empfänger möchte ich einen Zeitraum hinterlegen, an dem ich die Lieferung entgegennehmen kann

### ISSUE THREAD

**Issue by algenhirn** [MME-Aufgaben-im-Sommer-2022/mme-ss22-team-02#18]
Als User muss ich einen Zeitraum angeben in dem ich zuhause bin damit der "Lieferant" nicht vor verschlossener Tür steht, Außerdem muss der Antragssteller ja auch für die Produkte bei erhalt bezahlen.

**Comment by Cybun-s** [comment]
> Als User muss ich einen Zeitraum angeben in dem ich zuhause bin damit der "Lieferant" nicht vor verschlossener Tür steht, Außerdem muss der Antragssteller ja auch für die Produkte bei erhalt bezahlen.

Zeitraum kann von den Nutzern individuell per Chat besprochen werden. Funktion überflüssig.
