### ISSUE TITLE
Als Bringer/Empfänger möchte ich über Änderungen in der Anfrage benachrichtigt werden

### ISSUE THREAD

**Issue by algenhirn** [MME-Aufgaben-im-Sommer-2022/mme-ss22-team-02#19]
Ich will im oberen Bereich der Seite ein Glockensymbol haben welches mich über neue Aktivitäten benachrichtigt. Dort will ich z,B. darüber informiert werden wenn meine Anfrage angenommen wird oder wenn es eine neue Chatnachricht gibt

**Comment by Cybun-s** [comment]
Benachrichtigungssystem nicht implementiert.
