### ISSUE TITLE
Als Empfänger möchte ich eine Anfrage optional mit "nur wenn alles vorhanden" markieren können

### ISSUE THREAD

**Issue by Gerolmed** [MME-Aufgaben-im-Sommer-2022/mme-ss22-team-02#3]
Als Benutzer möchte ich Anhand der zur Verfügung stehenden Templates neue Anfragen erstellen. Ich möchte in der Lage sein einen spezifischen Markt an meine Anfrage zu knüpfen oder wenn mir das egal ist einfach nur ein oder mehrere Produkte. 
Außerdem muss es eine Option geben in der ich angeben kann, dass ich entweder alles auf der Liste oder auch einzelne Produkte brauche.
Möchte ich zum Beispiel einen Kuchen backen und brauche 7 Zutaten, hilft es mir nicht wenn ich nur 4 davon bekomme(weil sie z.B. ausverkauft sind). Daher ist diese Option wichtig.
(mit Name und key/val data)

**Comment by Cybun-s** [comment]
Funktion als überflüssig empfunden.
