### ISSUE TITLE
Als Empfänger möchte ich meine Adresse hinterlegen, um die Einkäufe empfangen zu können

### ISSUE THREAD

**Issue by Gerolmed** [MME-Aufgaben-im-Sommer-2022/mme-ss22-team-02#9]
Auf meinem Profil will ich meine Adresse eingeben können wenn ich mal eine Anfrage stelle. (Kein muss für User die nur Anfragen erfüllen)

**Comment by Cybun-s** [comment]
Individuell per Chat abstimmbar.
